kibot:
  version: 1

preflight:
  set_text_variables:
    - name: "date"
      command: git log -1 --format="%as"
    - name: "version"
      command: git describe --exact-match --tags 2> /dev/null || git rev-parse --short HEAD
  run_erc: true
  update_xml: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false
